version: '3.1'

services:
  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wishifieds_dev
    ports:
      - "5432:5432"

  # Can reference dynamic variables using ${MY_VAR}
  # Can set these before docker commands using something like:
    # $ MY_VAR=test docker-compose up
    # May need to pass "-p dev" or "-p test" to set property to run otherwise identical services
  # api:
  #   build: ../
  #   command: nf start
  #   image: wishifieds/dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres@db
